In [1]:
import numpy as np
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([0,1,1,1])
x,y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 1, 1]))

In [2]:
w=np.array([1,1])

In [3]:
w

array([1, 1])

In [4]:
b=-0.5

In [5]:
def activation(z):
    if z>=0:
        return 1
    else:
        return 0

In [6]:
pred=[]
for a in x:
    y_hat=np.dot(a,w)+b
    pred.append(activation(y_hat))

In [7]:
pred

[0, 1, 1, 1]

## perceptron Learning

In [8]:
import math

In [9]:
epochs=100
alpha=0.2

In [10]:
w0=np.random.random()
w1=np.random.random()
w2=np.random.random()
print("initial weights:")
print(f"wo= {w0}, w1= {w1}, w2= {w2}")

initial weights:
wo= 0.17149658503091192, w1= 0.9853124988497434, w2= 0.46649603512028437


In [11]:
del_wo=1
del_w1=1
del_w2=1

In [12]:
train_data_temp=[[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
train_data=np.asarray(train_data_temp)
op=np.array([0,1,1,1,1,1,1,1])

In [13]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [14]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

In [15]:
op.shape

(8,)

In [16]:
bias=0
for i in range(epochs):
    j=0
    for x in train_data:
        y_hat=w0*x[0]+w1*x[1]+w2*x[2]+bias
        if(y_hat>=0):
            act=1
        else:
            act=0
        err=op[j]-act
        del_wo=alpha*x[0]*err
        del_w1=alpha*x[1]*err
        del_w2=alpha*x[2]*err
        w0=w0+del_wo
        w1=w1+del_w1
        w2=w2+del_w2
        j+=1
#         print("epoch ",i+1,"error= ",err)
#         print(del_wo,del_w1,del_w2)
print("\nFinal weights = ")
print(f"w0 ={w0}, w1={w1}, w2={w2}")
        


Final weights = 
w0 =0.17149658503091192, w1=0.9853124988497434, w2=0.46649603512028437


## Types of Classification

## 1.Binary Classification
requires two classes, one in normal state and other in aberrant state
## 2.Multiclass Classification
Data points are grouped into several well known classes
## 3.MultiLabeled Classification
Features more than two class labels
## 4. Imbalanced Classification
Each class has different distribution


## Learner Type Terminology

## Lazy Learner
lazy learner delays the generalization of traning data until a query is made tomthe system
Examples: KNN
## Eager Learner
Before obtaining a test dataset,eager learners build a classification model using a traning dataset 
Examples:ANN,Naive Bayes

## sklearn classification Algorithms
## 01.Logistic Regression
Logistic regression algorithm is a supervised learning classification technique that forecasts the likelihood of a target variable
## 02.KNN algorithm 
the knn algorithm assumes that similar thing exist in close proximity
## 03.Decision Tree Algorithm
The goal of using a Decision Tree is to create a training model that cancan be used to predict the class or value of the target variable by learning simple decision rules inferred from prior data.
## 04.Random Forest
Random Forest is a classifier that contains a number of decision trees on various subsets of the given dataset and takes the average to improve the predictive accuracy of the dataset
## 05.Support Vector Machine 
The SVM algorithm creates the best line or decision boundary that can segregate n-dimmensional space into class
## 06.Naive Bayes
Naive Bayes classifier assumes that effect of a particular feeature in a class is independent of other features